<?php
/**
 
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2013 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
$_order = $this->getOrder();

$flubitOrder = False;

if ($_order->getFlubitOrderId()) {
    $flubitOrder = True;
}
?>
<?php $_items = $this->getCreditmemo()->getAllItems() ?>
<div class="grid np">
  <div class="hor-scroll">
    <table cellspacing="0" class="data order-tables">
        <col />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <thead>
            <tr class="headings">
                <th><?php echo $this->helper('sales')->__('Product') ?></th>
                <?php if($flubitOrder) { ?>
                    <th><?php echo $this->helper('sales')->__('Flubit Base Price') ?></th>
                <?php }?>
                <?php if($flubitOrder) { ?>
                    <th><?php echo $this->helper('sales')->__('Price Sold At(VAT inc.)') ?></th>
                <?php } else { ?>
                    <th><?php echo $this->helper('sales')->__('Price') ?></th>
                <?php } ?>
                <th class="a-center"><?php echo $this->helper('sales')->__('Qty') ?></th>
                <?php if(!$flubitOrder) { ?>
                <th><?php echo $this->helper('sales')->__('Subtotal') ?></th>
                <?php } ?>
                <?php if($flubitOrder) { ?>
                    <th><span class="nobr"><?php echo $this->helper('sales')->__('Tax Rate') ?></span></th>
                <?php } else { ?>
                    <th><span class="nobr"><?php echo $this->helper('sales')->__('Tax Amount') ?></span></th>
                <?php } ?>
                <th><span class="nobr"><?php echo $this->helper('sales')->__('Discount Amount') ?></span></th>
                <?php if($flubitOrder) { ?>
                    <th class="last"><span class="nobr"><?php echo $this->helper('sales')->__('Actual Price Sold At (VAT inc.)') ?></span></th>
                <?php } else { ?>
                    <th class="last"><span class="nobr"><?php echo $this->helper('sales')->__('Row Total') ?></span></th>
                <?php } ?>
            </tr>
        </thead>
        <?php $i=0;foreach ($_items as $_item): ?>
            <?php if ($_item->getOrderItem()->getParentItem()) continue; else $i++; ?>
            <tbody class="<?php echo $i%2?'even':'odd' ?>">
                <?php echo $this->getItemHtml($_item) ?>
                <?php echo $this->getItemExtraInfoHtml($_item->getOrderItem()) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
  </div>
</div>
<br />
